# Optional manual EE build for AAP 2.6. Production: use a pinned supported base image.
#
#   podman build -f Containerfile.example -t aap-ha-proxy-ee:lab .
#   podman push <registry>/aap-ha-proxy-ee:lab

FROM registry.redhat.io/ansible-automation-platform-26/ee-supported-rhel9:latest

USER root

COPY collections/requirements.yml /tmp/requirements.yml

RUN ansible-galaxy collection install -r /tmp/requirements.yml \
    -p /usr/share/ansible/collections

USER 1000
